### ISSUE TITLE
Sửa Thể Loại

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#14]
- Thiết kế giao diện:
Xuất hiện hộp thoại chứa thông tin thể hiện để tiến hành Thay Đổi: "Tên loại"
Bên dưới có 2 nút ", Quay Lại Trang Danh Sách"
- Xử lý:
Khi bấm vào nút "Thay Đổi" trên dòng chứa tên thể loại tại trang danh sách thể loại đối với người dùng có đăng nhập  sẽ xuất hiện thông báo trên để người dùng có thể 
Khi ấn vào nút "" hệ thống sẽ ghi nhận thông tin mà người dùng vừa nhập để tiến hành Thay Đổi thông tin của thể loại đó.
Khi ấn vào nút "Quay Lại Trang Danh Sách" sẽ về màn hình danh sách thể loại
- Lưu trữ:
Các thông tin vừa được Thay Đổi sẽ được lưu vào cơ sở dữ liệu.

**Comment by thaovale** [comment]
Đã kiểm tra các trường được nhập vào và thực hiện thay đổi trên Database.
