### ISSUE TITLE
Xóa Thể Loại

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#15]
Thiết kế giao diện: 
Hiển thị hộp thoại thông báo xác nhận có nội dung "Bạn có chắc chắc muốn xoá thể loại này?". Trong đó là 2 lựa chọn "Xoá, Quay lại"
- Thiết kế xử lý:
 Khi bấm vào nút "Xoá" trên dòng chứa tên thể loại tại trang danh sách thể loại đối với người dùng có đăng nhập  sẽ xuất hiện thông báo trên
Nếu chọn "Xoá" thể loại được chọn sẽ được xoá rồi trả về trang danh sách thể loại
Nếu chọn "Quay lại" sẽ ẩn hộp thoại và trả lại  trang danh sách thể loại
- Lưu trữ:
Khi người dùng xoá thì mọi thông tin của thể loại  đó sẽ bị xoá khỏi cơ sở dữ liệu.

**Comment by chiru24** [comment]
Đang làm

**Comment by chiru24** [comment]
Đã hoàn thành chức năng Xoá thể loại
