### ISSUE TITLE
Hiện Danh Sách Thể Loại

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#16]
-Thiết kế giao diện:
Tất cả thể loại được hiển thị tại thanh Navigation ( góc trái) ở  trang chủ
- Thiết kế xử lý:
Khi người dùng chọn một thể loại trên thanh Navigation sẽ đưa tới trang chứa các sách thuộc thể loại đó.
Đối với thủ thư đã đăng nhập:
-Thiết kế giao diện:
Tất cả thể loại được hiển thị tại thanh Navigation ở  trang chủ. Cuối cùng là nút cộng để thêm thể loại mới. Bên cạnh tên mỗi thể loại sẽ là nút Thay Đổi/xoá
Khi bấm vào nút "Thể loại" tại trang danh sách sách
- Thiết kế xử lý:
Khi người dùng chọn một thể loại trên thanh Navigation sẽ đưa tới trang chứa các sách thuộc thể loại đó.

**Comment by H-a-n-k** [comment]
làm rồi
