### ISSUE TITLE
Xem Danh Sách Sách

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#17]
-Thiết kế giao diện: dạng grid 4 cột
Bao gồm các thông tin: Hình ảnh sách, Tên sách, Tên tác giả
-Thiết kế xử lý:
Khi người dùng vào web thì sẽ hiển thị danh sách những cuốn sách có trong thư viện gồm những thông tin tên của mỗi cuốn sách
Đối với thủ thư đã đăng nhập:
-Thiết kế giao diện: dạng list
Bao gồm các thông tin: Hình ảnh sách, Tên sách, Tên tác giả, Tình trạng chung
Bên trên có nút "Thêm sách mới"
- -Thiết kế xử lý:
Khi người dùng chọn chức năng quản lý sách thì sẽ hiển thị danh sách những cuốn sách có trong thư viện gồm những thông tin tên của mỗi cuốn sách

**Comment by H-a-n-k** [comment]
làm rồi
