### ISSUE TITLE
Xem Chi Tiết Sách

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#19]
- Thiết kế giao diện:
Hiện các thông tin của sách: "Hình ảnh, Tên, Tác giả, tóm tắt, năm xuất bản, nhà xuất bản, tình trạng chung"
Bên dưới là danh sách các sách được mượn nhiều cùng thể loại
Đối với thủ thư đã đăng nhập:
- Thiết kế giao diện:
Hiện các thông tin của sách: "Hình ảnh, Tên, Tác giả, tóm tắt, năm xuất bản, nhà xuất bản, tình trạng chung, số lượng đầu sách, tình trạng từng đầu sách" 
Bên trên có nút "Thêm đầu sách" và thanh tìm kiếm đầu sách
Bên dưới có các nút "Thay Đổi, Xoá"
- Thiết kế xử lý
Khi người dùng bấm vào tên sách tại trang danh sách sách sẽ hiển thị trang chi tiết của sách đó kèm cái nút chức năng như trên.

**Comment by H-a-n-k** [comment]
làm rồi
