### ISSUE TITLE
Sửa Sách

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#20]
- Thiết kế giao diện: dạng form
Gồm những thông tin thể hiện : "Tên, Tác Giả, Số lượng, Tóm Tắt, Thể Loại, Ngày Sản xuất, Nhà Sản Xuất" của sách đó
Bên dưới có 2 nút ", Quay Lại Trang Danh Sách"
- Xử lý:
Khi bấm vào nút "Thay Đổi" trong trang chi tiết sách đối với người dùng có đăng nhập sẽ hiện trang chứa form có những thông tin trên của sách để người dùng có thể 
Khi ấn vào nút "" hệ thống sẽ ghi nhận thông tin mà người dùng vừa nhập để tiến hành Thay Đổi thông tin của sách đó.
Khi ấn vào nút "Quay Lại Trang Danh Sách" sẽ về màn hình chi tiết của sách đó
- Lưu trữ:
Các thông tin vừa được Thay Đổi sẽ được lưu vào cơ sở dữ liệu

**Comment by thaovale** [comment]
Đã chọn lọc, kiểm tra những trường được nhập vào. 
Đã thực hiện các thay đổi trên Database.
