### ISSUE TITLE
Xóa Sách

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#21]
- Thiết kế giao diện: 
Hiển thị hộp thoại thông báo xác nhận có nội dung "Bạn có chắc chắc muốn xoá Sách này?". Trong đó là 2 lựa chọn "Xoá, Quay lại"
- Thiết kế xử lý:
 Khi bấm vào nút "Xoá" trong trang chi tiết của sách sẽ xuất hiện thông báo trên
Nếu chọn "Xoá" sách được chọn sẽ được xoá rồi trả về trang danh sách sách
Nếu chọn "Quay lại" sẽ ẩn hộp thoại và trả lại trang chi tiết sách đó
- Lưu trữ:
Khi người dùng xoá thì mọi thông tin của sách  đó sẽ bị xoá khỏi cơ sở dữ liệu.

**Comment by chiru24** [comment]
Đã nhận Task

**Comment by chiru24** [comment]
Đã hoàn thành chức năng Xoá sách
