### ISSUE TITLE
Tìm kiếm Sách

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#22]
Thiết kế giao diện:
Có ô input ở trang danh sách sách
Bên cạnh có dropdownlist để hiển thị tùy chọn tìm kiếm theo title hoặc author
Bên dưới có list hiển thị gợi ý
Xử lý:
Khi nhập vào thanh tìm kiếm sẽ có hiện gợi ý phía dưới
Tự động cập nhật danh sách sách khi người dùng edit ô input
Lưu trữ:
Không thực hiện lưu trữ

**Comment by taikute** [comment]
*Xử lý: Tự động lọc theo thời gian thực luôn, không cần người dùng xác nhận "enter"
