### ISSUE TITLE
Thêm Đầu Sách

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#24]
- Thiết kế giao diện: Form
Thông tin thể hiện để tiến hành thêm: "Mã đầu sách, Trạng thái, Ghi chú"
Bên dưới có 2 nút "Thêm, Quay Lại"
- Thiết kế xử lý:
Khi bấm vào nút "Thêm đầu sách mới" trong trang chi tiết của một sách sẽ đưa tới trang chứa form thêm đầu sách mới
Khi ấn nút "Thêm" sau khi điền form , hệ thống sẽ kiểm tra thông tin nhập. Nếu hợp lệ đầu sách mới sẽ được thêm vào DB. Sau đó sẽ hiện hộp thoại thông báo "Thêm đầu sách thành công!". Nếu thông tin không hợp lệ người dùng buộc phải nhập lại.
Khi ấn nút "Quay Lại Trang Danh Sách" thì về màn hình chi tiết của sách đó
- Lưu trữ:
Lưu lại những thông đầu tin sách mới được người dùng nhập vào form lên cơ sở dữ liệu.

**Comment by chiru24** [comment]
Đã nhận Task

**Comment by chiru24** [comment]
Đã hoàn thành chức năng Thêm đầu sách
