### ISSUE TITLE
Sửa Đầu Sách

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#25]
- Thiết kế giao diện: dạng form
Gồm những thông tin thể hiện : "Trạng thái, Ghi chú" của một sách
Bên dưới có 2 nút ", Quay Lại Trang Danh Sách"
- Xử lý:
Khi bấm vào nút "Thay Đổi" trên dòng chứa đầu sách tại trang chi tiết của một sách đối với người dùng có đăng nhập sẽ hiện trang chứa form có những thông tin trên của đầu sách để người dùng có thể 
Khi ấn vào nút "" hệ thống sẽ ghi nhận thông tin mà người dùng vừa nhập để tiến hành Thay Đổi thông tin của đầu sách đó.
Khi ấn vào nút "Quay Lại Trang Danh Sách" sẽ về màn hình chi tiết của sách đó
- Lưu trữ:
Các thông tin vừa được Thay Đổi sẽ được lưu vào cơ sở dữ liệu.

**Comment by thaovale** [comment]
Đã hoàn thành.
