### ISSUE TITLE
Xoá Đầu Sách

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#26]
- Thiết kế giao diện: 
Hiển thị hộp thoại thông báo xác nhận có nội dung "Bạn có chắc chắc muốn xoá đầu sách này?". Trong đó là 2 lựa chọn "Xoá, Quay lại"
- Thiết kế xử lý:
 Khi bấm vào nút "Xoá" trên dòng chứa đầu sách tại trang chi tiết của một sách đối với người dùng có đăng nhập  sẽ xuất hiện thông báo trên
Nếu chọn "Xoá" đầu sách được chọn sẽ được xoá rồi trả về trang chi tiết của sách đó
Nếu chọn "Quay lại" sẽ ẩn hộp thoại và trả lại trang chi tiết sách đó
- Lưu trữ:
Khi người dùng xoá thì mọi thông tin của đầu sách  đó sẽ bị xoá khỏi cơ sở dữ liệu.

**Comment by chiru24** [comment]
Đã nhận Task

**Comment by chiru24** [comment]
Đã hoàn thành chức năng Xoá đầu sách
