### ISSUE TITLE
Tìm kiếm Đầu Sách

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#27]
Thiết kế giao diện: Ô input cho người dùng nhập thông tin
Xử lý: Khi người dùng nhập vào ô input, hệ thống tự động lọc và hiện ra danh sách đầu sách theo BookID
Lưu trữ: Không lưu trữ

**Comment by taikute** [comment]
Tìm kiếm đầu sách theo BookID

**Comment by taikute** [comment]
Tìm kiếm đầu sách theo LBookID

**Comment by taikute** [comment]
*Update: 
Giao diện: Mặc định
Xử lý: Sử dụng Jquery để bắt sự kiện input và cập nhật thông tin đầu sách trong bảng
