### ISSUE TITLE
Tạo Tài Khoản Thủ Thư

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#29]
- thiết kế giao diện:Form
Gồm những thông tin là: tên, giới tính, ngày tháng năm sinh, địa chỉ, email, tài khoản và Password (6~12 kí tự).  Bên dưới form có nút "Thêm".
- Xử lý:
Khi ấn nút "Thêm mới" tại trang xem danh sách thủ thư , hệ thống sẽ kiểm tra thông tin nhập. Nếu hợp lệ tài khoản mới sẽ được thêm vào DB. Sau đó sẽ hiện hộp thoại thông báo "Tạo thành công!". Nếu thông tin không hợp lệ người dùng buộc phải nhập lại.
Khi ấn nút "Quay Lại Trang Danh Sách" thì về màn hình chính.
- Lưu trữ:
Lưu lại những thông tin tài khoản mới được người dùng nhập vào form lên DB.

**Comment by JoanDND** [comment]
Đang làm
