### ISSUE TITLE
Đăng Nhập

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#30]
- thiết kế giao diện : Khi nhấn vào nút đăng nhập. Form đăng nhập hiện ra kiểu dialog
Có tiêu đề "ĐĂNG NHẬP" ở trên cùng form.
Bên dưới là các trường Tên người dùng và Mật khẩu (6 ->12 kí tự) để người dùng nhập tài khoản và mật khẩu.
Bên dưới có 2 nút "Đăng nhập, Quay Lại Trang Danh Sách".
-Xử lý:
Khi ấn "Đăng nhập" thì hệ thống tiến hành kiểm tra Tên người dùng và mật khẩu, nếu có thông tin trùng khớp thì cho phép đăng nhập vào hệ thống -> quay lại trang chủ, nếu sai thì hiện thông báo sai thông tin. 
Khi ấn "Quay Lại Trang Danh Sách" thì ẩn form đăng nhập.
- Lưu trữ: (???)
Thông tin từ Tên người dùng và Mật khẩu  nhập vào sẽ được lưu trữ tạm thời để hệ thống kiểm tra thông tin có khớp với tài khoản nào đang được lưu trữ không

**Comment by H-a-n-k** [comment]
đã nhận task
