### ISSUE TITLE
Sửa Thông Tin Tài Khoản Thủ Thư

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#32]
- Thiết kế giao diện: dạng form
Gồm những thông tin thể hiện : "Tên thủ thư, Tình trạng, Giới tính, Ngày sinh, Địa chỉ, Số điện thoại, Email" của mỗi thủ thư
Bên dưới có 2 nút "Thay đổi", Quay Lại Trang Danh Sách"
- Xử lý:
Khi bấm vào nút "thay đổi" trong trang danh sách thủ thư sẽ hiện form chứa những tất cả thông tin trên của thủ thư để người dùng có thể 
Khi ấn vào nút "thay đổi" hệ thống ghi nhận thông tin mà người dùng vừa nhập nếu hợp lệ và báo lỗi nếu không hợp lệ.
Khi ấn vào nút "Quay Lại Trang Danh Sách" sẽ về màn hình chính sau khi đăng nhập của quản trị viên
- Lưu trữ:
Các thông tin vừa được Thay Đổi sẽ được lưu vào cơ sở dữ liệu.

**Comment by thaovale** [comment]
Đã hoàn thành.
