### ISSUE TITLE
Khóa Tài Khoản Thủ Thư

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#34]
- Thiết kế giao diện:
Hiện hộp thoại thông báo "Xác định khoá tài khỏan thủ thư này" hoặc "Xác định mở khoá tài khoản thủ thư này?" với hai lựa chọn là "Đồng ý" và "Huỷ"
- Xử lý:
Khi bấm vào nút "Tình Trạng" trong trang danh sách thủ thư sẽ tiến hành thiết lập tình trạng của tài khoản đó
Có 2 lựa chọn: "Khoá tài khoản/ Mở khoá tài khoản"
- Lưu trữ: 
Lúc này thông tin về tình trạng của tài khoản thủ thư sẽ được lưu trữ, khi có bất kì  nào về trang thái của tài khoản thì đều sẽ được cập nhật trong cơ sở dữ liệu.

**Comment by thaovale** [comment]
Đã nhận task.

**Comment by thaovale** [comment]
Đã hoàn thành.
