### ISSUE TITLE
Tạo Thẻ Thư Viện

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#35]
- Thiết kế giao diện: Form
Thông tin thể hiện để tiến hành thêm: "Mã thẻ, Tên đọc giả, Giới tính, Ngày sinh, Thời hạn, Tình trạng, Số lần vi phạm"
Bên dưới có 2 nút "Thêm, Quay Lại"
- Thiết kế xử lý:
Khi bấm vào nút "Thêm thẻ thư viện" trong trang danh thẻ thư viện sẽ đưa tới trang chứa form thêm đọc giả mới
Khi ấn nút "Thêm" sau khi điền form , hệ thống sẽ kiểm tra thông tin nhập. Nếu hợp lệ sách độc giả mới sẽ được thêm vào DB. Sau đó sẽ hiện hộp thoại thông báo "Thêm the thư viện thành công!". Nếu thông tin không hợp lệ người dùng buộc phải nhập lại.
Khi ấn nút "Quay Lại Trang Danh Sách" thì về màn hình danh sách độc giả
- Lưu trữ:
Lưu lại những thông tin độc giả mới được người dùng nhập vào form lên cơ sở dữ liệu.

**Comment by chiru24** [comment]
Đã nhận Task

**Comment by chiru24** [comment]
Đã hoàn thành
