### ISSUE TITLE
Sửa Thông Tin Thẻ Thư Viện

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#36]
- Thiết kế giao diện: dạng form
Xuất hiện hộp thoại chứa thông tin thể hiện để tiến hành Thay Đổi: "Mã thẻ, Tên đọc giả, Giới tính, Ngày sinh, Thời hạn, Tình trạng"
Bên dưới có 2 nút ", Quay Lại Trang Danh Sách"
- Xử lý:
Khi bấm vào nút "Thay Đổi" trên dòng chứa thông tin thẻ th tại trang danh sách thẻ thư viện đối với người dùng có đăng nhập  sẽ xuất hiện thông báo trên để người dùng có thể 
Khi ấn vào nút "" hệ thống sẽ ghi nhận thông tin mà người dùng vừa nhập để tiến hành Thay Đổi thông tin của thẻ thư viện đó.
Khi ấn vào nút "Quay Lại Trang Danh Sách" sẽ về màn hình danh sách thẻ thưu viện
- Lưu trữ:
Các thông tin vừa được Thay Đổi sẽ được lưu vào cơ sở dữ liệu.

**Comment by thaovale** [comment]
Đã hoàn thành.
