### ISSUE TITLE
Khóa Thẻ Thư Viện

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#37]
- Thiết kế giao diện:
Hiện hộp thoại thông báo "Xác định khoá thẻ tài khoản này" hoặc "Xác định mở thẻ thư viện này?" với hai lựa chọn là "Đồng ý" và "Huỷ"
- Xử lý:
Khi bấm vào nút "Tình Trạng" trong trang danh sách thẻ thư viện sẽ tiến hành thiết lập tình trạng của thẻ đó
Có 2 lựa chọn: "Khoá thẻ/ Mở khoá thẻ"
- Lưu trữ: 
Lúc này thông tin về tình trạng củathẻ thư viện sẽ được lưu trữ, khi có bất kì  nào về trang thái của thẻ thì đều sẽ được cập nhật trong cơ sở dữ liệu.

**Comment by chiru24** [comment]
Đã hoàn thành
