### ISSUE TITLE
Xem danh sách Thẻ Thư Viện

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#38]
- Thiết kế giao diện: Dạng list
Thông tin thể hiện   "Mã thẻ, Tên đọc giả, Giới tính, Ngày sinh, Thời hạn, Tình trạng, Số lần vi phạm"
- Thiết kế xử lý: 
Khi người dùng chọn hiển thị danh sách tất cả các thẻ thư viện đã tạo

**Comment by H-a-n-k** [comment]
đã nhận task
