### ISSUE TITLE
Danh sách phiếu mượn

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#40]
- Thiết kế giao diện: Dạng list
Thông tin thể hiện  "Số thứ tự, Tên sách, Mã đầu sách, Tên độc giả, Ngày mượn, Ngày trả, Ghi chú"
Bên trên là nút "Thêm phiếu mượn"
- Thiết kế xử lý: 
Khi người dùng chọn hiển thị danh sách phiếu mượn sẽ hiển thị toàn bộ phiếu mượn đã được tạo ra

**Comment by H-a-n-k** [comment]
đang làm
