### ISSUE TITLE
Tạo Phiếu Mượn

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#41]
**Thiết kế giao diện**: dạng Form
Thông tin thể hiện để tiến hành thêm: "Tên sách, Mã đầu sách, Tên độc giả, Ngày mượn, Ngày trả, Ghi chú"
Bên dưới có 2 nút "Thêm, Quay Lại"
**Thiết kế xử lý**
Khi bấm vào nút "Thêm thẻ thư viện" trong trang danh thẻ thư viện sẽ đưa tới trang chứa form thêm đọc giả mới
Khi ấn nút "Thêm" sau khi điền form , hệ thống sẽ kiểm tra thông tin nhập. Nếu hợp lệ sách độc giả mới sẽ được thêm vào DB. Sau đó sẽ hiện hộp thoại thông báo "Thêm thẻ thư viện thành công!". Nếu thông tin không hợp lệ người dùng buộc phải nhập lại.
Khi ấn nút "Quay Lại Trang Danh Sách" thì về màn hình danh sách thẻ thư viện
**Thiết Kế Lưu trữ**:
Lưu lại những thông tin độc giả mới được người dùng nhập vào form lên cơ sở dữ liệu ở bảng CallCards.

**Comment by taikute** [comment]
#76

**Comment by tranviendai** [comment]
đã check
