### ISSUE TITLE
Xem Chi Tiết Phạt Của Một Người

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#44]
- Thiết kế giao diện: Form
Hiện danh sách lịch sử bị phạt gồm mã thẻ thư viện, tên độc giả, ngày, tên sách, lý do, số tiền phạt, đã đóng tiền phạt chưa
- Thiết kể xử lý:
Khi người dùng tìm kiếm bằng mã thẻ thư viện thì sẽ  dẫn đến trang chứa những form phạt của độc giả có mã thẻ thư viện đó tương ứng. 
- Lưu trữ:
Khi thủ thư sử dụng chức năng này, tất cả thông tin  sẽ được lấy từ cơ sở dữ liệu ra

**Comment by JoanDND** [comment]
Nhận task
