### ISSUE TITLE
Cập Nhật Phạt 

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#45]
- Thiết kế giao diện: Form
Thông tin hiển thị: họ tên người mượn, ngày lập phiếu, số tiền phạt, đầu sách đã mượn, lý do phạt. (Chỉ cho phép  thông tin của Field "Lý Do")
Bên dưới có nút "Quay lại" và "Cập Nhật Phiếu"
- Thiết kế xử lý:
Sau khi người dùng chọn nút Cập nhật tại trang chi tiết phạt của một phiếu phạt thì sẽ hiển thị form trên
Khi người dùng chọn nút "Cập nhật phiếu" mọi thông tin sẽ được ghi lại vào cơ sở dữ liệu
Bấm nút "Quay lại" sẽ trả về trang chi tiết phạt 
- Lưu trữ:
Các thông tin vừa được Thay Đổi sẽ được lưu vào cơ sở dữ liệu.

**Comment by JoanDND** [comment]
Nhận task
