### ISSUE TITLE
Xem Thống Kê Báo Cáo

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#46]
**Thiết kế giao diện**
Các báo cáo thống kê sẽ được hiển thị dạng biểu đồ
Thông tin được hiển thị bao gồm: Số lượng sách hiện tại trong thư viện, số lượng độc giả đăng ký thẻ thư viện, số lượng sách được mượn trong một năm, những cuốn sách được mượn nhiều trong năm, những cuốn sách ít được mượn trong năm, sách bị hư hỏng cần được thanh lý, số lần độc giả vi phạm, tổng phí phạt từ độc giả, thời gian báo cáo.
**Thiết kế xử lý**
Khi quản trị viên xử dụng chức năng xem thống kê báo cáo sẽ chọn vào mục muốn xem theo từng năm, chi tiết của các bản báo cáo thống kê lúc được thể hiện cụ thể mọi chức năng được liệt kê trên

**Comment by taikute** [comment]
Đã nhận

**Comment by tranviendai** [comment]
đã check
