### ISSUE TITLE
Tra cứu lịch sử mượn sách

### ISSUE THREAD

**Issue by tranviendai** [tranviendai/Librarian#50]
-Thiết kế giao diện:
Trang chủ có thanh tìm kiếm mã thẻ thư viện
Trang lịch sử mượn sách có Tên độc giả, danh sách những sách đang và từng mượn gồm ngày mượn, tên sách, ngày trả, tình trạng (trễ hạn/sách hỏng/mất,...)
- Thiết kế xử lý:
Khi người dùng nhập mã thẻ hệ thống sẽ kiểm tra mã thẻ có đúng không. Nếu đúng sẽ đến trang lịch sử mượn của độc giả đó, nếu sai phải nhập lại

**Comment by JoanDND** [comment]
Nhận task
